variable provider_version {}
variable bigips {}
variable name {}
variable partition {}
variable template_name {}
variable application_language {}
variable enforcement_mode {}
variable server_technologies {}
variable parameters {}
variable signatures {}
variable modifications {}
variable tags {}
